### ISSUE TITLE
罕见的AMD-V项目

### ISSUE THREAD

**Issue by Jhran** [Liu-Zhiying/StartAMDVHookDriverFromNone#1]
github上我见到过的AMD-V项目一只手都可以数的过来，VT项目书籍漫天飞，AMD-V冷清清，这对我这个初学者来说不友好到家了，我都开始怀疑现在是不是2003年了，作者速更啊，急需参考。

**Comment by Liu-Zhiying** [comment]
谢谢，自己都快咕咕咕了，不过既然有人想看，那就竭尽全力
