### ISSUE TITLE
性能损耗是正常的吗？

### ISSUE THREAD

**Issue by BaiFeng666** [Liu-Zhiying/StartAMDVHookDriverFromNone#2]
Debug编译 虚拟机加载正常 

就是整个系统感觉从60FPS变成了30FPS，这是正常的吗

**Comment by Liu-Zhiying** [comment]
首先逆是用的NPT HOOK功能吗？如果是MSR HOOK应该没啥问题，如果是NPT HOOK的话我测试是Hook ExAllocatePool2函数，这个函数是频繁调用的，所以影响性能，还有尽量使用物理机跑，VMWare的AMD嵌套虚拟化本身就性能堪忧，
这点SimpleHook作者也提到过

**Comment by BaiFeng666** [comment]
我是用的默认的NPT Hook
MSR Hook性能更优秀吗？我刚接触虚拟化 不太了解...

**Comment by Liu-Zhiying** [comment]
倒不是优秀不优秀的问题




芯
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Liu-Zhiying/StartAMDVHookDriverFromNone"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年11月2日(星期六) 凌晨3:20
***@***.***&gt;;
***@***.***&gt;;"State ***@***.***&gt;;
主题:&nbsp;Re: [Liu-Zhiying/StartAMDVHookDriverFromNone] 性能损耗是正常的吗？ (Issue #2)





 
我是用的默认的NPT Hook
 MSR Hook性能更优秀吗？我刚接触虚拟化 不太了解...

**Comment by Liu-Zhiying** [comment]
NPT HOOK 用来HOOK 内核API
MSR HOOK 用来HOOK Syscall
主要是尽量用物理机，因为虚拟机的嵌套虚拟化性能顺市很大，还有换别的API hook试试




芯
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Liu-Zhiying/StartAMDVHookDriverFromNone"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年11月2日(星期六) 凌晨3:20
***@***.***&gt;;
***@***.***&gt;;"State ***@***.***&gt;;
主题:&nbsp;Re: [Liu-Zhiying/StartAMDVHookDriverFromNone] 性能损耗是正常的吗？ (Issue #2)





 
我是用的默认的NPT Hook
 MSR Hook性能更优秀吗？我刚接触虚拟化 不太了解...

**Comment by BaiFeng666** [comment]
谢谢解答 在物理机上尝试了下 还是比较流畅的！
